[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | __pycache__
  | migrations
  | _pb2\.py
  | _pb2_grpc\.py
)/
'''

[tool.isort]
profile = "black"
line_length = 120
skip_glob = ["*/migrations/*", "*_pb2.py", "*_pb2_grpc.py"]
known_django = "django"
known_first_party = ["products", "orders", "core", "ecommerce_grpc"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pylint.messages_control]
disable = "C0330, C0326"
max-line-length = 120

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
exclude = [
    "migrations",
    "venv",
    "env",
    "_pb2.py",
    "_pb2_grpc.py"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "ecommerce_grpc.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "--reuse-db --nomigrations"
